---

- name: run server
  hosts: server
  become: true

  vars:
    docker_practice_repo: "https://github.com/ormabyshev/DockerPractice.git"
    repo_branch: "develop"
    work_dir: "/opc/server"
  
  tasks:
    - name: install git
      apt:
        name: git
        state: present
    
    - name: git clone
      git:
        repo: "{{docker_practice_repo}}"
        dest: "{{work_dir}}"
        version: "{{repo_branch}}"
        force: yes

    - name: update config telegraf
      replace:
        path: "{{work_dir}}/vms/server/telegraf/telegraf.conf"
        regexp: 'servers = \["tcp://192\.168\.31\.247:1883"\]'
        replace: 'servers = ["tcp://{{broker_private_ip}}:1883"]'

    - name: run server containers
      community.docker.docker_compose_v2:
        project_src: "{{work_dir}}/vms/server"
        state: present

    - name: wait for InfluxDB to start 15 sek
      pause:
        seconds: 15
    
    - name: create database in influxdb
      community.docker.docker_container_exec:
        container: influxdb
        command: influx -execute "CREATE DATABASE sensors"
        
    - name: create user in influxdb
      community.docker.docker_container_exec:
        container: influxdb
        command: influx -execute "CREATE USER telegraf WITH PASSWORD 'telegraf' WITH ALL PRIVILEGES"
      
    - name: restart telegraf that it can connect to influxdb with new credentials
      shell: docker restart telegraf

        